import { Category, Product } from "@/types";

export const mockCategories: Category[] = [
  { id: "1", name: "Beauty", slug: "beauty", display_order: 1, image_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80" },
  { id: "2", name: "Home Essentials", slug: "home-essentials", display_order: 2, image_url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80" },
  { id: "3", name: "Tech", slug: "tech", display_order: 3, image_url: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80" },
  { id: "4", name: "Handmade", slug: "handmade", display_order: 4, image_url: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&q=80" },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Premium Ceramic Coffee Dripper",
    slug: "premium-ceramic-coffee-dripper",
    short_description: "Elevate your morning routine with this handcrafted ceramic pour-over coffee dripper.",
    description: "Detailed description goes here...",
    image_url: "https://images.unsplash.com/photo-1544426577-628d0979a0b1?w=800&q=80",
    affiliate_link: "#",
    platform: "Amazon",
    category_id: "2",
    category: mockCategories[1],
    price: 34.99,
    badge: "Editor's Pick",
    featured: true,
    handmade: false,
    why_i_recommend: "I use this every single morning. It extracts the perfect flavor and looks beautiful on my counter.",
    display_order: 1,
  },
  {
    id: "2",
    title: "Minimalist Resin Coasters (Set of 4)",
    slug: "minimalist-resin-coasters",
    short_description: "Hand-poured resin coasters with subtle gold leaf accents.",
    description: "Detailed description goes here...",
    image_url: "https://images.unsplash.com/photo-1617391741544-77e8a3ffb104?w=800&q=80",
    affiliate_link: "#",
    platform: "Other",
    category_id: "4",
    category: mockCategories[3],
    price: 28.00,
    featured: false,
    handmade: true,
    display_order: 2,
  },
  {
    id: "3",
    title: "Hydrating Vitamin C Serum",
    slug: "hydrating-vitamin-c-serum",
    short_description: "A lightweight, brightening serum that leaves your skin glowing all day.",
    description: "Detailed description goes here...",
    image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    affiliate_link: "#",
    platform: "Amazon",
    category_id: "1",
    category: mockCategories[0],
    price: 45.00,
    badge: "Trending",
    featured: false,
    handmade: false,
    display_order: 3,
  },
  {
    id: "4",
    title: "Ergonomic Desk Chair",
    slug: "ergonomic-desk-chair",
    short_description: "The ultimate work-from-home companion for perfect posture.",
    description: "Detailed description goes here...",
    image_url: "https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=800&q=80",
    affiliate_link: "#",
    platform: "Flipkart",
    category_id: "3",
    category: mockCategories[2],
    price: 199.99,
    featured: false,
    handmade: false,
    display_order: 4,
  }
];
